spring.application.name=SpringCloud-Bus-Kafka

#config-service
spring.config.import=configserver:http://localhost:8763
spring.cloud.config.username=configUser
spring.cloud.config.password=password
spring.cloud.config.name=${spring.application.name}
spring.cloud.config.label=1.0.0

#retry-config
spring.cloud.config.fail-fast=false
spring.cloud.config.retry.max-attempts=6
spring.cloud.config.retry.max-interval=2000
spring.cloud.config.retry.initial-interval=1000

spring.kafka.bootstrap-servers=localhost:9092
management.endpoints.web.exposure.include=busrefresh